apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: f5-2
spec:
  # Provide the controller name as "f5.com/cntr-ingress-svcs"
  # Warning: don't change the controller name as cis verify the controller name while processing the ingress resource
  controller: f5.com/cntr-ingress-svcs