apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: foo-virtual-server
  namespace: F5-CIS-2 #second f5 namespace
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: foo.example.com
  ipamLabel: "f5-2"
  virtualServerName: "foo-virtual-server"
  pools:
  - path: /
    service: foo-service
    serviceNamespace: default
    servicePort: 80